/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 78e797eb722b1d6547a71afa50d914f1)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	EMAIL: SendEmail;
	DEMO_MODE: "1";
	MAIL_PROVIDER: "demo";
	MAIL_FROM: "auth@opensesh.io";
	BETTER_AUTH_SECRET: string;
	DATABASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEMO_MODE" | "MAIL_PROVIDER" | "MAIL_FROM" | "BETTER_AUTH_SECRET" | "DATABASE_URL">> {}
}
