/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 213f2ccf9cbe87a1b389bb8eec472730)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	EMAIL: SendEmail;
	APP_ORIGIN: "https://app.opensesh.io";
	DEMO_MODE: "1";
	MAIL_PROVIDER: "demo";
	MAIL_FROM: "auth@opensesh.io";
	BETTER_AUTH_SECRET: string;
	DATABASE_URL: string;
	ANTHROPIC_API_KEY?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "DEMO_MODE" | "MAIL_PROVIDER" | "MAIL_FROM" | "BETTER_AUTH_SECRET" | "DATABASE_URL" | "ANTHROPIC_API_KEY">> {}
}
