packages:
  - apps/*
  - packages/*

allowBuilds:
  es5-ext: false
  esbuild: true
  lightningcss: true
  msgpackr-extract: true
  sharp: true
  vue-demi: false
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - lightningcss
  - msgpackr-extract
  - sharp
  - workerd
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vite-plus: 0.2.8
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260810.1'
  - '@cloudflare/nimbus-docs@0.10.0'
patchedDependencies:
  react-server-dom-webpack@19.2.8: patches/react-server-dom-webpack@19.2.8.patch
