import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import nimbus, { defineConfig as defineNimbusConfig } from "@cloudflare/nimbus-docs";
import { tableScroll } from "@cloudflare/nimbus-docs/markdown";

const nimbusConfig = defineNimbusConfig({
  site: "https://docs.opensesh.io",
  title: "opensesh docs",
  description:
    "Documentation for opensesh — the open program OS for conferences. Call for papers, review, agenda, speakers, and embeds, self-hosted on Cloudflare Workers.",
  locale: "en",
  github: null,
  socialImageAlt: "opensesh documentation preview",
  head: [
    {
      tag: "link",
      attrs: { rel: "icon", type: "image/svg+xml", href: "/brand/opensesh-mark.svg" },
    },
  ],
  sidebar: {
    items: [
      {
        label: "Overview",
        items: ["index", "getting-started", "deployment"],
      },
      {
        label: "Guides",
        items: [
          "guides/call-for-papers",
          "guides/submissions",
          "guides/evaluation",
          "guides/sessions",
          "guides/speakers",
          "guides/speaker-portal",
          "guides/agenda",
          "guides/widgets",
          "guides/email",
          "guides/integrations",
          "guides/workspace",
        ],
      },
      // Autogenerated so `api/index.mdx` becomes the group's landing link;
      // child order comes from each page's `sidebar.order` frontmatter.
      { label: "API reference", autogenerate: { directory: "api" } },
      { label: "app.opensesh.io", link: "https://app.opensesh.io" },
    ],
  },
});

export default defineConfig({
  output: "static",
  // Tailwind v4 via its Vite plugin (the integration Astro recommends for
  // Tailwind v4 — replaces the PostCSS plugin, which doesn't build under
  // Astro 7's Vite 8 bundler).
  vite: {
    plugins: [tailwindcss()],
  },
  // Hover-prefetch link targets so full-page navigations feel instant without
  // a client-side router.
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "hover",
  },
  integrations: [
    nimbus(nimbusConfig, {
      // Authoring rules are opt-in by design — your repo, your taste. The
      // two below are the load-bearing pair: frontmatter has to validate
      // against the content schema for the page to render properly, and
      // broken internal links are 404s for your readers. Add the others
      // (heading hierarchy, code-block language, style, etc.) when you're
      // ready to enforce them — see `nimbus-docs lint --help`.
      rules: {
        "nimbus/frontmatter-shape": "error",
        "nimbus/internal-link": "error",
      },
      // Wrap wide tables so they scroll instead of overflowing the page
      // (styled by `.nb-table-scroll` in src/styles/prose.css).
      markdown: {
        hastPlugins: [tableScroll()],
      },
    }),
  ],
});
