/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ERouteImport } from './routes/e'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as AdminAbstractsRouteImport } from './routes/admin.abstracts'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminEvaluationRouteImport } from './routes/admin.evaluation'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminSpeakersRouteImport } from './routes/admin.speakers'
import { Route as AdminWidgetsRouteImport } from './routes/admin.widgets'
import { Route as ESplatRouteImport } from './routes/e.$'
import { Route as EEventSlugRouteImport } from './routes/e.$eventSlug'
import { Route as EmbedEmbedIdRouteImport } from './routes/embed.$embedId'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalSectionRouteImport } from './routes/portal.$section'
import { Route as SubmitSplatRouteImport } from './routes/submit.$'
import { Route as AdminAbstractsIdRouteImport } from './routes/admin.abstracts_.$id'
import { Route as AdminFormsFormIdRouteImport } from './routes/admin.forms.$formId'
import { Route as AdminPortalFormsFormIdRouteImport } from './routes/admin.portal-forms.$formId'
import { Route as AdminSettingsEventRouteImport } from './routes/admin.settings.event'
import { Route as AdminSettingsLibraryRouteImport } from './routes/admin.settings.library'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as EEventSlugIndexRouteImport } from './routes/e.$eventSlug.index'
import { Route as EEventSlugAgendaRouteImport } from './routes/e.$eventSlug.agenda'
import { Route as EEventSlugItineraryRouteImport } from './routes/e.$eventSlug.itinerary'
import { Route as EEventSlugSessionsRouteImport } from './routes/e.$eventSlug.sessions'
import { Route as EEventSlugSpeakersRouteImport } from './routes/e.$eventSlug.speakers'
import { Route as EventAssetsEventIdIconRouteImport } from './routes/event-assets.$eventId.icon'
import { Route as SubmitEventSlugFormIdRouteImport } from './routes/submit.$eventSlug.$formId'
import { Route as EEventSlugSessionsCodeRouteImport } from './routes/e.$eventSlug.sessions_.$code'
import { Route as EEventSlugSpeakersGalleryRouteImport } from './routes/e.$eventSlug.speakers_.gallery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ERoute = ERouteImport.update({
  id: '/e',
  path: '/e',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbstractsRoute = AdminAbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluationRoute = AdminEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWidgetsRoute = AdminWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AdminRoute,
} as any)
const ESplatRoute = ESplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ERoute,
} as any)
const EEventSlugRoute = EEventSlugRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => ERoute,
} as any)
const EmbedEmbedIdRoute = EmbedEmbedIdRouteImport.update({
  id: '/embed/$embedId',
  path: '/embed/$embedId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSectionRoute = PortalSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PortalRoute,
} as any)
const SubmitSplatRoute = SubmitSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SubmitRoute,
} as any)
const AdminAbstractsIdRoute = AdminAbstractsIdRouteImport.update({
  id: '/abstracts_/$id',
  path: '/abstracts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsFormIdRoute = AdminFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminPortalFormsFormIdRoute = AdminPortalFormsFormIdRouteImport.update({
  id: '/portal-forms/$formId',
  path: '/portal-forms/$formId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsEventRoute = AdminSettingsEventRouteImport.update({
  id: '/settings/event',
  path: '/settings/event',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsLibraryRoute = AdminSettingsLibraryRouteImport.update({
  id: '/settings/library',
  path: '/settings/library',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EEventSlugIndexRoute = EEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EEventSlugRoute,
} as any)
const EEventSlugAgendaRoute = EEventSlugAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => EEventSlugRoute,
} as any)
const EEventSlugItineraryRoute = EEventSlugItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => EEventSlugRoute,
} as any)
const EEventSlugSessionsRoute = EEventSlugSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => EEventSlugRoute,
} as any)
const EEventSlugSpeakersRoute = EEventSlugSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => EEventSlugRoute,
} as any)
const EventAssetsEventIdIconRoute = EventAssetsEventIdIconRouteImport.update({
  id: '/event-assets/$eventId/icon',
  path: '/event-assets/$eventId/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitEventSlugFormIdRoute = SubmitEventSlugFormIdRouteImport.update({
  id: '/$eventSlug/$formId',
  path: '/$eventSlug/$formId',
  getParentRoute: () => SubmitRoute,
} as any)
const EEventSlugSessionsCodeRoute = EEventSlugSessionsCodeRouteImport.update({
  id: '/sessions_/$code',
  path: '/sessions/$code',
  getParentRoute: () => EEventSlugRoute,
} as any)
const EEventSlugSpeakersGalleryRoute =
  EEventSlugSpeakersGalleryRouteImport.update({
    id: '/speakers_/gallery',
    path: '/speakers/gallery',
    getParentRoute: () => EEventSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/e': typeof ERouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/submit': typeof SubmitRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/abstracts': typeof AdminAbstractsRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/e/$': typeof ESplatRoute
  '/e/$eventSlug': typeof EEventSlugRouteWithChildren
  '/embed/$embedId': typeof EmbedEmbedIdRoute
  '/portal/$section': typeof PortalSectionRoute
  '/submit/$': typeof SubmitSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/abstracts/$id': typeof AdminAbstractsIdRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/admin/portal-forms/$formId': typeof AdminPortalFormsFormIdRoute
  '/admin/settings/event': typeof AdminSettingsEventRoute
  '/admin/settings/library': typeof AdminSettingsLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/e/$eventSlug/agenda': typeof EEventSlugAgendaRoute
  '/e/$eventSlug/itinerary': typeof EEventSlugItineraryRoute
  '/e/$eventSlug/sessions': typeof EEventSlugSessionsRoute
  '/e/$eventSlug/speakers': typeof EEventSlugSpeakersRoute
  '/event-assets/$eventId/icon': typeof EventAssetsEventIdIconRoute
  '/submit/$eventSlug/$formId': typeof SubmitEventSlugFormIdRoute
  '/e/$eventSlug/': typeof EEventSlugIndexRoute
  '/e/$eventSlug/sessions/$code': typeof EEventSlugSessionsCodeRoute
  '/e/$eventSlug/speakers/gallery': typeof EEventSlugSpeakersGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e': typeof ERouteWithChildren
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/abstracts': typeof AdminAbstractsRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/e/$': typeof ESplatRoute
  '/embed/$embedId': typeof EmbedEmbedIdRoute
  '/portal/$section': typeof PortalSectionRoute
  '/submit/$': typeof SubmitSplatRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/abstracts/$id': typeof AdminAbstractsIdRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/admin/portal-forms/$formId': typeof AdminPortalFormsFormIdRoute
  '/admin/settings/event': typeof AdminSettingsEventRoute
  '/admin/settings/library': typeof AdminSettingsLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/e/$eventSlug/agenda': typeof EEventSlugAgendaRoute
  '/e/$eventSlug/itinerary': typeof EEventSlugItineraryRoute
  '/e/$eventSlug/sessions': typeof EEventSlugSessionsRoute
  '/e/$eventSlug/speakers': typeof EEventSlugSpeakersRoute
  '/event-assets/$eventId/icon': typeof EventAssetsEventIdIconRoute
  '/submit/$eventSlug/$formId': typeof SubmitEventSlugFormIdRoute
  '/e/$eventSlug': typeof EEventSlugIndexRoute
  '/e/$eventSlug/sessions/$code': typeof EEventSlugSessionsCodeRoute
  '/e/$eventSlug/speakers/gallery': typeof EEventSlugSpeakersGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/e': typeof ERouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/submit': typeof SubmitRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/abstracts': typeof AdminAbstractsRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/widgets': typeof AdminWidgetsRoute
  '/e/$': typeof ESplatRoute
  '/e/$eventSlug': typeof EEventSlugRouteWithChildren
  '/embed/$embedId': typeof EmbedEmbedIdRoute
  '/portal/$section': typeof PortalSectionRoute
  '/submit/$': typeof SubmitSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/abstracts_/$id': typeof AdminAbstractsIdRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/admin/portal-forms/$formId': typeof AdminPortalFormsFormIdRoute
  '/admin/settings/event': typeof AdminSettingsEventRoute
  '/admin/settings/library': typeof AdminSettingsLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/e/$eventSlug/agenda': typeof EEventSlugAgendaRoute
  '/e/$eventSlug/itinerary': typeof EEventSlugItineraryRoute
  '/e/$eventSlug/sessions': typeof EEventSlugSessionsRoute
  '/e/$eventSlug/speakers': typeof EEventSlugSpeakersRoute
  '/event-assets/$eventId/icon': typeof EventAssetsEventIdIconRoute
  '/submit/$eventSlug/$formId': typeof SubmitEventSlugFormIdRoute
  '/e/$eventSlug/': typeof EEventSlugIndexRoute
  '/e/$eventSlug/sessions_/$code': typeof EEventSlugSessionsCodeRoute
  '/e/$eventSlug/speakers_/gallery': typeof EEventSlugSpeakersGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/e'
    | '/login'
    | '/portal'
    | '/submit'
    | '/admin/$section'
    | '/admin/abstracts'
    | '/admin/agenda'
    | '/admin/communications'
    | '/admin/emails'
    | '/admin/evaluation'
    | '/admin/forms'
    | '/admin/sessions'
    | '/admin/speakers'
    | '/admin/widgets'
    | '/e/$'
    | '/e/$eventSlug'
    | '/embed/$embedId'
    | '/portal/$section'
    | '/submit/$'
    | '/admin/'
    | '/portal/'
    | '/admin/abstracts/$id'
    | '/admin/forms/$formId'
    | '/admin/portal-forms/$formId'
    | '/admin/settings/event'
    | '/admin/settings/library'
    | '/api/auth/$'
    | '/e/$eventSlug/agenda'
    | '/e/$eventSlug/itinerary'
    | '/e/$eventSlug/sessions'
    | '/e/$eventSlug/speakers'
    | '/event-assets/$eventId/icon'
    | '/submit/$eventSlug/$formId'
    | '/e/$eventSlug/'
    | '/e/$eventSlug/sessions/$code'
    | '/e/$eventSlug/speakers/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e'
    | '/login'
    | '/submit'
    | '/admin/$section'
    | '/admin/abstracts'
    | '/admin/agenda'
    | '/admin/communications'
    | '/admin/emails'
    | '/admin/evaluation'
    | '/admin/forms'
    | '/admin/sessions'
    | '/admin/speakers'
    | '/admin/widgets'
    | '/e/$'
    | '/embed/$embedId'
    | '/portal/$section'
    | '/submit/$'
    | '/admin'
    | '/portal'
    | '/admin/abstracts/$id'
    | '/admin/forms/$formId'
    | '/admin/portal-forms/$formId'
    | '/admin/settings/event'
    | '/admin/settings/library'
    | '/api/auth/$'
    | '/e/$eventSlug/agenda'
    | '/e/$eventSlug/itinerary'
    | '/e/$eventSlug/sessions'
    | '/e/$eventSlug/speakers'
    | '/event-assets/$eventId/icon'
    | '/submit/$eventSlug/$formId'
    | '/e/$eventSlug'
    | '/e/$eventSlug/sessions/$code'
    | '/e/$eventSlug/speakers/gallery'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/e'
    | '/login'
    | '/portal'
    | '/submit'
    | '/admin/$section'
    | '/admin/abstracts'
    | '/admin/agenda'
    | '/admin/communications'
    | '/admin/emails'
    | '/admin/evaluation'
    | '/admin/forms'
    | '/admin/sessions'
    | '/admin/speakers'
    | '/admin/widgets'
    | '/e/$'
    | '/e/$eventSlug'
    | '/embed/$embedId'
    | '/portal/$section'
    | '/submit/$'
    | '/admin/'
    | '/portal/'
    | '/admin/abstracts_/$id'
    | '/admin/forms/$formId'
    | '/admin/portal-forms/$formId'
    | '/admin/settings/event'
    | '/admin/settings/library'
    | '/api/auth/$'
    | '/e/$eventSlug/agenda'
    | '/e/$eventSlug/itinerary'
    | '/e/$eventSlug/sessions'
    | '/e/$eventSlug/speakers'
    | '/event-assets/$eventId/icon'
    | '/submit/$eventSlug/$formId'
    | '/e/$eventSlug/'
    | '/e/$eventSlug/sessions_/$code'
    | '/e/$eventSlug/speakers_/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ERoute: typeof ERouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SubmitRoute: typeof SubmitRouteWithChildren
  EmbedEmbedIdRoute: typeof EmbedEmbedIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  EventAssetsEventIdIconRoute: typeof EventAssetsEventIdIconRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e': {
      id: '/e'
      path: '/e'
      fullPath: '/e'
      preLoaderRoute: typeof ERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abstracts': {
      id: '/admin/abstracts'
      path: '/abstracts'
      fullPath: '/admin/abstracts'
      preLoaderRoute: typeof AdminAbstractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluation': {
      id: '/admin/evaluation'
      path: '/evaluation'
      fullPath: '/admin/evaluation'
      preLoaderRoute: typeof AdminEvaluationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/widgets': {
      id: '/admin/widgets'
      path: '/widgets'
      fullPath: '/admin/widgets'
      preLoaderRoute: typeof AdminWidgetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$': {
      id: '/e/$'
      path: '/$'
      fullPath: '/e/$'
      preLoaderRoute: typeof ESplatRouteImport
      parentRoute: typeof ERoute
    }
    '/e/$eventSlug': {
      id: '/e/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/e/$eventSlug'
      preLoaderRoute: typeof EEventSlugRouteImport
      parentRoute: typeof ERoute
    }
    '/embed/$embedId': {
      id: '/embed/$embedId'
      path: '/embed/$embedId'
      fullPath: '/embed/$embedId'
      preLoaderRoute: typeof EmbedEmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$section': {
      id: '/portal/$section'
      path: '/$section'
      fullPath: '/portal/$section'
      preLoaderRoute: typeof PortalSectionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/submit/$': {
      id: '/submit/$'
      path: '/$'
      fullPath: '/submit/$'
      preLoaderRoute: typeof SubmitSplatRouteImport
      parentRoute: typeof SubmitRoute
    }
    '/admin/abstracts_/$id': {
      id: '/admin/abstracts_/$id'
      path: '/abstracts/$id'
      fullPath: '/admin/abstracts/$id'
      preLoaderRoute: typeof AdminAbstractsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms/$formId': {
      id: '/admin/forms/$formId'
      path: '/$formId'
      fullPath: '/admin/forms/$formId'
      preLoaderRoute: typeof AdminFormsFormIdRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/portal-forms/$formId': {
      id: '/admin/portal-forms/$formId'
      path: '/portal-forms/$formId'
      fullPath: '/admin/portal-forms/$formId'
      preLoaderRoute: typeof AdminPortalFormsFormIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/event': {
      id: '/admin/settings/event'
      path: '/settings/event'
      fullPath: '/admin/settings/event'
      preLoaderRoute: typeof AdminSettingsEventRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/library': {
      id: '/admin/settings/library'
      path: '/settings/library'
      fullPath: '/admin/settings/library'
      preLoaderRoute: typeof AdminSettingsLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$eventSlug/': {
      id: '/e/$eventSlug/'
      path: '/'
      fullPath: '/e/$eventSlug/'
      preLoaderRoute: typeof EEventSlugIndexRouteImport
      parentRoute: typeof EEventSlugRoute
    }
    '/e/$eventSlug/agenda': {
      id: '/e/$eventSlug/agenda'
      path: '/agenda'
      fullPath: '/e/$eventSlug/agenda'
      preLoaderRoute: typeof EEventSlugAgendaRouteImport
      parentRoute: typeof EEventSlugRoute
    }
    '/e/$eventSlug/itinerary': {
      id: '/e/$eventSlug/itinerary'
      path: '/itinerary'
      fullPath: '/e/$eventSlug/itinerary'
      preLoaderRoute: typeof EEventSlugItineraryRouteImport
      parentRoute: typeof EEventSlugRoute
    }
    '/e/$eventSlug/sessions': {
      id: '/e/$eventSlug/sessions'
      path: '/sessions'
      fullPath: '/e/$eventSlug/sessions'
      preLoaderRoute: typeof EEventSlugSessionsRouteImport
      parentRoute: typeof EEventSlugRoute
    }
    '/e/$eventSlug/speakers': {
      id: '/e/$eventSlug/speakers'
      path: '/speakers'
      fullPath: '/e/$eventSlug/speakers'
      preLoaderRoute: typeof EEventSlugSpeakersRouteImport
      parentRoute: typeof EEventSlugRoute
    }
    '/event-assets/$eventId/icon': {
      id: '/event-assets/$eventId/icon'
      path: '/event-assets/$eventId/icon'
      fullPath: '/event-assets/$eventId/icon'
      preLoaderRoute: typeof EventAssetsEventIdIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$eventSlug/$formId': {
      id: '/submit/$eventSlug/$formId'
      path: '/$eventSlug/$formId'
      fullPath: '/submit/$eventSlug/$formId'
      preLoaderRoute: typeof SubmitEventSlugFormIdRouteImport
      parentRoute: typeof SubmitRoute
    }
    '/e/$eventSlug/sessions_/$code': {
      id: '/e/$eventSlug/sessions_/$code'
      path: '/sessions/$code'
      fullPath: '/e/$eventSlug/sessions/$code'
      preLoaderRoute: typeof EEventSlugSessionsCodeRouteImport
      parentRoute: typeof EEventSlugRoute
    }
    '/e/$eventSlug/speakers_/gallery': {
      id: '/e/$eventSlug/speakers_/gallery'
      path: '/speakers/gallery'
      fullPath: '/e/$eventSlug/speakers/gallery'
      preLoaderRoute: typeof EEventSlugSpeakersGalleryRouteImport
      parentRoute: typeof EEventSlugRoute
    }
  }
}

interface AdminFormsRouteChildren {
  AdminFormsFormIdRoute: typeof AdminFormsFormIdRoute
}

const AdminFormsRouteChildren: AdminFormsRouteChildren = {
  AdminFormsFormIdRoute: AdminFormsFormIdRoute,
}

const AdminFormsRouteWithChildren = AdminFormsRoute._addFileChildren(
  AdminFormsRouteChildren,
)

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminAbstractsRoute: typeof AdminAbstractsRoute
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminEvaluationRoute: typeof AdminEvaluationRoute
  AdminFormsRoute: typeof AdminFormsRouteWithChildren
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminWidgetsRoute: typeof AdminWidgetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAbstractsIdRoute: typeof AdminAbstractsIdRoute
  AdminPortalFormsFormIdRoute: typeof AdminPortalFormsFormIdRoute
  AdminSettingsEventRoute: typeof AdminSettingsEventRoute
  AdminSettingsLibraryRoute: typeof AdminSettingsLibraryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminAbstractsRoute: AdminAbstractsRoute,
  AdminAgendaRoute: AdminAgendaRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminEvaluationRoute: AdminEvaluationRoute,
  AdminFormsRoute: AdminFormsRouteWithChildren,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminWidgetsRoute: AdminWidgetsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAbstractsIdRoute: AdminAbstractsIdRoute,
  AdminPortalFormsFormIdRoute: AdminPortalFormsFormIdRoute,
  AdminSettingsEventRoute: AdminSettingsEventRoute,
  AdminSettingsLibraryRoute: AdminSettingsLibraryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EEventSlugRouteChildren {
  EEventSlugAgendaRoute: typeof EEventSlugAgendaRoute
  EEventSlugItineraryRoute: typeof EEventSlugItineraryRoute
  EEventSlugSessionsRoute: typeof EEventSlugSessionsRoute
  EEventSlugSpeakersRoute: typeof EEventSlugSpeakersRoute
  EEventSlugIndexRoute: typeof EEventSlugIndexRoute
  EEventSlugSessionsCodeRoute: typeof EEventSlugSessionsCodeRoute
  EEventSlugSpeakersGalleryRoute: typeof EEventSlugSpeakersGalleryRoute
}

const EEventSlugRouteChildren: EEventSlugRouteChildren = {
  EEventSlugAgendaRoute: EEventSlugAgendaRoute,
  EEventSlugItineraryRoute: EEventSlugItineraryRoute,
  EEventSlugSessionsRoute: EEventSlugSessionsRoute,
  EEventSlugSpeakersRoute: EEventSlugSpeakersRoute,
  EEventSlugIndexRoute: EEventSlugIndexRoute,
  EEventSlugSessionsCodeRoute: EEventSlugSessionsCodeRoute,
  EEventSlugSpeakersGalleryRoute: EEventSlugSpeakersGalleryRoute,
}

const EEventSlugRouteWithChildren = EEventSlugRoute._addFileChildren(
  EEventSlugRouteChildren,
)

interface ERouteChildren {
  ESplatRoute: typeof ESplatRoute
  EEventSlugRoute: typeof EEventSlugRouteWithChildren
}

const ERouteChildren: ERouteChildren = {
  ESplatRoute: ESplatRoute,
  EEventSlugRoute: EEventSlugRouteWithChildren,
}

const ERouteWithChildren = ERoute._addFileChildren(ERouteChildren)

interface PortalRouteChildren {
  PortalSectionRoute: typeof PortalSectionRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSectionRoute: PortalSectionRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SubmitRouteChildren {
  SubmitSplatRoute: typeof SubmitSplatRoute
  SubmitEventSlugFormIdRoute: typeof SubmitEventSlugFormIdRoute
}

const SubmitRouteChildren: SubmitRouteChildren = {
  SubmitSplatRoute: SubmitSplatRoute,
  SubmitEventSlugFormIdRoute: SubmitEventSlugFormIdRoute,
}

const SubmitRouteWithChildren =
  SubmitRoute._addFileChildren(SubmitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ERoute: ERouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SubmitRoute: SubmitRouteWithChildren,
  EmbedEmbedIdRoute: EmbedEmbedIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  EventAssetsEventIdIconRoute: EventAssetsEventIdIconRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
