/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ERouteImport } from './routes/e'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as AdminAbstractsRouteImport } from './routes/admin.abstracts'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminEvaluationRouteImport } from './routes/admin.evaluation'
import { Route as AdminFormsRouteImport } from './routes/admin.forms'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as ESplatRouteImport } from './routes/e.$'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalSectionRouteImport } from './routes/portal.$section'
import { Route as SubmitSplatRouteImport } from './routes/submit.$'
import { Route as AdminAbstractsIdRouteImport } from './routes/admin.abstracts_.$id'
import { Route as AdminFormsFormIdRouteImport } from './routes/admin.forms.$formId'
import { Route as AdminSettingsEventRouteImport } from './routes/admin.settings.event'
import { Route as AdminSettingsLibraryRouteImport } from './routes/admin.settings.library'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SubmitEventSlugFormIdRouteImport } from './routes/submit.$eventSlug.$formId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ERoute = ERouteImport.update({
  id: '/e',
  path: '/e',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbstractsRoute = AdminAbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEvaluationRoute = AdminEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsRoute = AdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const ESplatRoute = ESplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ERoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSectionRoute = PortalSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => PortalRoute,
} as any)
const SubmitSplatRoute = SubmitSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SubmitRoute,
} as any)
const AdminAbstractsIdRoute = AdminAbstractsIdRouteImport.update({
  id: '/abstracts_/$id',
  path: '/abstracts/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsFormIdRoute = AdminFormsFormIdRouteImport.update({
  id: '/$formId',
  path: '/$formId',
  getParentRoute: () => AdminFormsRoute,
} as any)
const AdminSettingsEventRoute = AdminSettingsEventRouteImport.update({
  id: '/settings/event',
  path: '/settings/event',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsLibraryRoute = AdminSettingsLibraryRouteImport.update({
  id: '/settings/library',
  path: '/settings/library',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitEventSlugFormIdRoute = SubmitEventSlugFormIdRouteImport.update({
  id: '/$eventSlug/$formId',
  path: '/$eventSlug/$formId',
  getParentRoute: () => SubmitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/e': typeof ERouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/submit': typeof SubmitRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/abstracts': typeof AdminAbstractsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/e/$': typeof ESplatRoute
  '/portal/$section': typeof PortalSectionRoute
  '/submit/$': typeof SubmitSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/abstracts/$id': typeof AdminAbstractsIdRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/admin/settings/event': typeof AdminSettingsEventRoute
  '/admin/settings/library': typeof AdminSettingsLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/submit/$eventSlug/$formId': typeof SubmitEventSlugFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e': typeof ERouteWithChildren
  '/login': typeof LoginRoute
  '/submit': typeof SubmitRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/abstracts': typeof AdminAbstractsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/e/$': typeof ESplatRoute
  '/portal/$section': typeof PortalSectionRoute
  '/submit/$': typeof SubmitSplatRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/abstracts/$id': typeof AdminAbstractsIdRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/admin/settings/event': typeof AdminSettingsEventRoute
  '/admin/settings/library': typeof AdminSettingsLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/submit/$eventSlug/$formId': typeof SubmitEventSlugFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/e': typeof ERouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/submit': typeof SubmitRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/abstracts': typeof AdminAbstractsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/admin/forms': typeof AdminFormsRouteWithChildren
  '/admin/sessions': typeof AdminSessionsRoute
  '/e/$': typeof ESplatRoute
  '/portal/$section': typeof PortalSectionRoute
  '/submit/$': typeof SubmitSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/abstracts_/$id': typeof AdminAbstractsIdRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRoute
  '/admin/settings/event': typeof AdminSettingsEventRoute
  '/admin/settings/library': typeof AdminSettingsLibraryRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/submit/$eventSlug/$formId': typeof SubmitEventSlugFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/e'
    | '/login'
    | '/portal'
    | '/submit'
    | '/admin/$section'
    | '/admin/abstracts'
    | '/admin/emails'
    | '/admin/evaluation'
    | '/admin/forms'
    | '/admin/sessions'
    | '/e/$'
    | '/portal/$section'
    | '/submit/$'
    | '/admin/'
    | '/portal/'
    | '/admin/abstracts/$id'
    | '/admin/forms/$formId'
    | '/admin/settings/event'
    | '/admin/settings/library'
    | '/api/auth/$'
    | '/submit/$eventSlug/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e'
    | '/login'
    | '/submit'
    | '/admin/$section'
    | '/admin/abstracts'
    | '/admin/emails'
    | '/admin/evaluation'
    | '/admin/forms'
    | '/admin/sessions'
    | '/e/$'
    | '/portal/$section'
    | '/submit/$'
    | '/admin'
    | '/portal'
    | '/admin/abstracts/$id'
    | '/admin/forms/$formId'
    | '/admin/settings/event'
    | '/admin/settings/library'
    | '/api/auth/$'
    | '/submit/$eventSlug/$formId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/e'
    | '/login'
    | '/portal'
    | '/submit'
    | '/admin/$section'
    | '/admin/abstracts'
    | '/admin/emails'
    | '/admin/evaluation'
    | '/admin/forms'
    | '/admin/sessions'
    | '/e/$'
    | '/portal/$section'
    | '/submit/$'
    | '/admin/'
    | '/portal/'
    | '/admin/abstracts_/$id'
    | '/admin/forms/$formId'
    | '/admin/settings/event'
    | '/admin/settings/library'
    | '/api/auth/$'
    | '/submit/$eventSlug/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ERoute: typeof ERouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SubmitRoute: typeof SubmitRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e': {
      id: '/e'
      path: '/e'
      fullPath: '/e'
      preLoaderRoute: typeof ERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abstracts': {
      id: '/admin/abstracts'
      path: '/abstracts'
      fullPath: '/admin/abstracts'
      preLoaderRoute: typeof AdminAbstractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluation': {
      id: '/admin/evaluation'
      path: '/evaluation'
      fullPath: '/admin/evaluation'
      preLoaderRoute: typeof AdminEvaluationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms': {
      id: '/admin/forms'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/e/$': {
      id: '/e/$'
      path: '/$'
      fullPath: '/e/$'
      preLoaderRoute: typeof ESplatRouteImport
      parentRoute: typeof ERoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$section': {
      id: '/portal/$section'
      path: '/$section'
      fullPath: '/portal/$section'
      preLoaderRoute: typeof PortalSectionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/submit/$': {
      id: '/submit/$'
      path: '/$'
      fullPath: '/submit/$'
      preLoaderRoute: typeof SubmitSplatRouteImport
      parentRoute: typeof SubmitRoute
    }
    '/admin/abstracts_/$id': {
      id: '/admin/abstracts_/$id'
      path: '/abstracts/$id'
      fullPath: '/admin/abstracts/$id'
      preLoaderRoute: typeof AdminAbstractsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms/$formId': {
      id: '/admin/forms/$formId'
      path: '/$formId'
      fullPath: '/admin/forms/$formId'
      preLoaderRoute: typeof AdminFormsFormIdRouteImport
      parentRoute: typeof AdminFormsRoute
    }
    '/admin/settings/event': {
      id: '/admin/settings/event'
      path: '/settings/event'
      fullPath: '/admin/settings/event'
      preLoaderRoute: typeof AdminSettingsEventRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/library': {
      id: '/admin/settings/library'
      path: '/settings/library'
      fullPath: '/admin/settings/library'
      preLoaderRoute: typeof AdminSettingsLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/$eventSlug/$formId': {
      id: '/submit/$eventSlug/$formId'
      path: '/$eventSlug/$formId'
      fullPath: '/submit/$eventSlug/$formId'
      preLoaderRoute: typeof SubmitEventSlugFormIdRouteImport
      parentRoute: typeof SubmitRoute
    }
  }
}

interface AdminFormsRouteChildren {
  AdminFormsFormIdRoute: typeof AdminFormsFormIdRoute
}

const AdminFormsRouteChildren: AdminFormsRouteChildren = {
  AdminFormsFormIdRoute: AdminFormsFormIdRoute,
}

const AdminFormsRouteWithChildren = AdminFormsRoute._addFileChildren(
  AdminFormsRouteChildren,
)

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminAbstractsRoute: typeof AdminAbstractsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminEvaluationRoute: typeof AdminEvaluationRoute
  AdminFormsRoute: typeof AdminFormsRouteWithChildren
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAbstractsIdRoute: typeof AdminAbstractsIdRoute
  AdminSettingsEventRoute: typeof AdminSettingsEventRoute
  AdminSettingsLibraryRoute: typeof AdminSettingsLibraryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminAbstractsRoute: AdminAbstractsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminEvaluationRoute: AdminEvaluationRoute,
  AdminFormsRoute: AdminFormsRouteWithChildren,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAbstractsIdRoute: AdminAbstractsIdRoute,
  AdminSettingsEventRoute: AdminSettingsEventRoute,
  AdminSettingsLibraryRoute: AdminSettingsLibraryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ERouteChildren {
  ESplatRoute: typeof ESplatRoute
}

const ERouteChildren: ERouteChildren = {
  ESplatRoute: ESplatRoute,
}

const ERouteWithChildren = ERoute._addFileChildren(ERouteChildren)

interface PortalRouteChildren {
  PortalSectionRoute: typeof PortalSectionRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalSectionRoute: PortalSectionRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SubmitRouteChildren {
  SubmitSplatRoute: typeof SubmitSplatRoute
  SubmitEventSlugFormIdRoute: typeof SubmitEventSlugFormIdRoute
}

const SubmitRouteChildren: SubmitRouteChildren = {
  SubmitSplatRoute: SubmitSplatRoute,
  SubmitEventSlugFormIdRoute: SubmitEventSlugFormIdRoute,
}

const SubmitRouteWithChildren =
  SubmitRoute._addFileChildren(SubmitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ERoute: ERouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SubmitRoute: SubmitRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
